# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1b93259630540a8f0704387e52cd4745b93a3a0b920e7cafc43d89c590210d15bca64ec699185530bb61f78d50bf1c9fd12c82034d1bafdbe9d034d63997452

test:
  secret_key_base: ac6d6bad7b1b81d1d0a908196680b7a8797ed43d753007e929f9bea51e6199e80c4f09c5a21b4e887cdfe8e601eb05d09e6713f8e4c1e0606b85df6be4803169

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
